# Generated by Django 5.1.6 on 2025-05-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_author_user_en_us_author_user_ru_category_name_en_us_and_more'),
    ]

    operations = [
    ]
