# Generated by Django 5.1.6 on 2025-05-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20250504_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user_en_us',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_ru',
        ),
    ]
